name: anzu
url: http://matchi.moe
highlighter: rouge
permalink: posts/:title
exclude: ['Rakefile', 'README.md', 'config.rb', 'CNAME']
authors:
  Matchi-chan:
    display_name: Matchi-chan
    twitter: Matchi_chan
    github: Matchi-chan
    url: https://twitter.com/Matchi_chan
